/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Base.gltf 
*/

import React, {  useRef, useState} from 'react'
import { useGLTF } from '@react-three/drei'

const Base = (props: any) => {
  const { nodes, materials } = useGLTF('/newmodels/Base.gltf') as any
  return (
    <group {...props} dispose={null}>
      <mesh
          geometry={nodes.Cube.geometry}
          material={materials['Material.026']}
          position={[-12.416, 17.467, -19.861]}
          scale={[0.755, 0.178, 0.755]}
      />
    </group>
  )
}
export default Base

useGLTF.preload('/newmodels/Base.gltf')
