/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Button1.gltf 
*/

import React, { useRef, useState} from 'react'
import { useGLTF } from '@react-three/drei'

const Button1 = (props: any) => {
  const { nodes, materials } = useGLTF('/newmodels/Button1.gltf') as any
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder003.geometry} material={materials['Material.009']} position={[-5.75, 17.729, 4.957]} scale={[0.493, 0.072, 0.493]} />
    </group>
  )
}
export default Button1

useGLTF.preload('/newmodels/Button1.gltf')
