/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Button.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Button = (props: any) => {
  const { nodes, materials } = useGLTF('/newmodels/Button.gltf') as any
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Material.009']} position={[-12.418, 17.729, 4.861]} scale={[0.493, 0.072, 0.493]} />
    </group>
  )
}
export default Button

useGLTF.preload('/newmodels/Button.gltf')
