/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Contact2Lamp.gltf 
*/

import React, {useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'

const Contact2Lamp = (props: any) => {
  const { nodes, materials } = useGLTF('/newmodels/Contact2Lamp.gltf') as any
  return (
    <group {...props} dispose={null}>
      <group
          position={[-7.741, 17.568, -19.837]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.06, -0.025, -0.06]}
      >
        <mesh
            geometry={nodes['Изолятор_контакта_#1003'].geometry}
            material={materials['Material.009']}
        />
        <mesh
            geometry={nodes['Изолятор_контакта_#1003_1'].geometry}
            material={materials['Material.007']}
        />
      </group>
    </group>
  )
}
export default Contact2Lamp
useGLTF.preload('/newmodels/Contact2Lamp.gltf')
