/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Contacts.gltf 
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'

const Contacts = (props: any) => {
  const { nodes, materials } = useGLTF('/newmodels/Contacts.gltf') as any
  return (
    <group {...props} dispose={null}>
      <mesh
          geometry={nodes.Основа_контакта_2.geometry}
          material={materials['Material.007']}
          position={[0.684, 19.582, -19.723]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={[-0.047, -0.003, -0.047]} />
    </group>
  )
}
export default Contacts
useGLTF.preload('/newmodels/Contacts.gltf')
