/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Contact1Capacitor.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Contact1Capacitor1 = (props: any) => {
  const { nodes, materials } = useGLTF('/newmodels/Contact1Capacitor.gltf') as any
  return (
    <group {...props} dispose={null}>
      <group position={[-3.241, 17.662, 6.123]} rotation={[-1.57, 0, Math.PI]} scale={[-0.099, -0.007, -0.099]}>
        <mesh geometry={nodes.Основа_контакта_2004.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Основа_контакта_2004_1.geometry} material={materials['Material.009']} />
      </group>
    </group>
  )
}
export default Contact1Capacitor1
useGLTF.preload('/newmodels/Contact1Capacitor.gltf')
