/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 LampHolder.gltf 
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'

const LampHolder = (props: any) => {
  const { nodes, materials } = useGLTF('/newmodels/LampHolder.gltf') as any
  return (
    <group {...props} dispose={null}>
      <mesh
          geometry={nodes.Cylinder004.geometry}
          material={materials['Material.002']}
          position={[-7.728, 17.402, -19.838]}
          scale={[0.57, 0.051, 0.57]}
      />
    </group>
  )
}
export default LampHolder
useGLTF.preload('/newmodels/LampHolder.gltf')
