/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Pipe.gltf 
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'

const Pipe = (props: any) => {
  const { nodes, materials } = useGLTF('/newmodels/Pipe.gltf') as any
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Цилиндр_пушки.geometry} material={materials['Material.011']} position={[2.87, 19.533, 6.664]} rotation={[0, 0, -Math.PI / 2]} scale={1.619} />
    </group>
  )
}
export default Pipe
useGLTF.preload('/newmodels/Pipe.gltf')
