/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 RegulatorBase.gltf 
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'

const RegulatorBase = (props: any) => {
  const { nodes, materials } = useGLTF('/newmodels/RegulatorBase.gltf') as any
  return (
    <group {...props} dispose={null}>
      <mesh
          geometry={nodes.Коробка_напряжения.geometry}
          material={nodes.Коробка_напряжения.material}
          position={[-14.893, 17.602, -19.9]}
          rotation={[0, -1.571, 0]}
          scale={[1, 0.32, 1]}
      />
    </group>
  )
}
export default RegulatorBase
useGLTF.preload('/newmodels/RegulatorBase.gltf')
