/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 RegulatorButton.gltf 
*/

import React, {useEffect, useRef, useState} from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const RegulatorButton = (props: any) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/newmodels/RegulatorButton.gltf') as any
  const { actions } = useAnimations(animations, group)
  const [click, setClick] = useState<boolean>(false)
  const [active, setActive] = useState<boolean>(false)
  useEffect(()=>{
    console.log(group.current)
  })
  const getButton = () => {
    setClick(!click)
      setActive(!active)
  }
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
            name="Регулятор_напряжения"
            geometry={nodes.Регулятор_напряжения.geometry}
            material={materials['Material.011']}
            position={!click ? [-14.923, 17.877, -19.708] : [-14.923, 17.977, -19.708]}
            scale={[0.608, 0.09, 0.608]}
            onClick={getButton}
        >
            <meshStandardMaterial  color={!active ? "red" : "black"}/>
        </mesh>
      </group>
    </group>
  )
}
export default RegulatorButton
useGLTF.preload('/newmodels/RegulatorButton.gltf')
