/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Scene.gltf 
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'

const Scene = (props: any) => {
  const { nodes, materials } = useGLTF('/newmodels/Scene.gltf') as any
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane001.geometry} material={materials['Wood Flooring']} position={[-1.416, 0.469, 6.603]} scale={80.313} />
      <mesh geometry={nodes.Plane002.geometry} material={materials['Striped Wallpaper']} position={[0.19, 80.379, -73.925]} rotation={[Math.PI / 2, 0, 0]} scale={[84.002, 86.971, 86.971]} />
      <mesh geometry={nodes.Plane003.geometry} material={materials['Striped Wallpaper']} position={[78.17, 79.863, 5.752]} rotation={[Math.PI/2, 0, -Math.PI / 2]} scale={[83.909, 86.772, 86.772]} />
      <mesh geometry={nodes.Plane004.geometry} material={materials['Striped Wallpaper']} position={[-81.567, 80.379, 6.529]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={84.414} />
      <mesh geometry={nodes.Plane005.geometry} material={materials['Striped Wallpaper']} position={[0.331, 80.379, 86.206]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[84.417, 85.869, 85.869]} />
      <mesh geometry={nodes.Wall_Book_Shelf001.geometry} material={materials['Material.027']} position={[-50.525, 0.469, 79.374]} rotation={[Math.PI, 0, Math.PI]} scale={21.246} />
      <mesh geometry={nodes.Wall_Book_Shelf002.geometry} material={materials['Material.027']} position={[-71.322, 0.469, 79.374]} rotation={[Math.PI, 0, Math.PI]} scale={21.246} />
      <mesh geometry={nodes.Wall_Book_Shelf003.geometry} material={materials['Material.027']} position={[67.748, 0.469, 79.374]} rotation={[Math.PI, 0, Math.PI]} scale={21.246} />
      <mesh geometry={nodes.Wall_Book_Shelf004.geometry} material={materials['Material.027']} position={[46.952, 0.469, 79.374]} rotation={[Math.PI, 0, Math.PI]} scale={21.246} />
      <group position={[-51.479, 23.603, 77.57]} rotation={[1.57, 0.337, 1.578]} scale={29.866}>
        <mesh geometry={nodes.Cube015_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube015_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[-44.613, 23.592, 77.45]} rotation={[1.568, 0.338, 1.578]} scale={29.866}>
        <mesh geometry={nodes.Cube011_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube011_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[-47.197, 23.671, 77.492]} rotation={[1.569, 0.183, 1.579]} scale={29.866}>
        <mesh geometry={nodes.Cube011_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube011_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[-45.459, 23.16, 77.705]} rotation={[1.567, 0.323, 1.579]} scale={29.866}>
        <mesh geometry={nodes.Cube012_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube012_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[-43.958, 23.664, 77.573]} rotation={[1.568, 0.339, 1.578]} scale={29.866}>
        <mesh geometry={nodes.Cube013_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube013_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[-46.564, 23.769, 77.456]} rotation={[1.569, 0.184, 1.579]} scale={29.866}>
        <mesh geometry={nodes.Cube013_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube013_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[-43.39, 23.518, 77.418]} rotation={[1.576, 0.343, 1.575]} scale={29.866}>
        <mesh geometry={nodes.Cube014_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube014_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[-47.711, 23.744, 77.511]} rotation={[1.569, 0.181, 1.58]} scale={29.866}>
        <mesh geometry={nodes.Cube010_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube010_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[-51.802, 23.16, 77.705]} rotation={[1.567, 0.323, 1.579]} scale={29.866}>
        <mesh geometry={nodes.Cube016_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube016_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[-50.302, 23.664, 77.573]} rotation={[1.568, 0.339, 1.578]} scale={29.866}>
        <mesh geometry={nodes.Cube017_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube017_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[-52.908, 23.769, 77.456]} rotation={[1.569, 0.184, 1.579]} scale={29.866}>
        <mesh geometry={nodes.Cube017_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube017_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[-49.734, 23.518, 77.418]} rotation={[1.576, 0.343, 1.575]} scale={29.866}>
        <mesh geometry={nodes.Cube018_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube018_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[-53.541, 23.671, 77.492]} rotation={[1.569, 0.183, 1.579]} scale={29.866}>
        <mesh geometry={nodes.Cube019_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube019_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[-57.727, 31.549, 77.57]} rotation={[1.57, 0.337, 1.578]} scale={29.866}>
        <mesh geometry={nodes.Cube020_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube020_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[-58.05, 31.105, 77.705]} rotation={[1.567, 0.323, 1.579]} scale={29.866}>
        <mesh geometry={nodes.Cube021_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube021_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[-56.55, 31.609, 77.573]} rotation={[1.568, 0.339, 1.578]} scale={29.866}>
        <mesh geometry={nodes.Cube022_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube022_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[-59.156, 31.715, 77.456]} rotation={[1.569, 0.184, 1.579]} scale={29.866}>
        <mesh geometry={nodes.Cube022_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube022_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[-59.789, 31.616, 77.492]} rotation={[1.569, 0.183, 1.579]} scale={29.866}>
        <mesh geometry={nodes.Cube024_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube024_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[-57.727, 15.553, 77.57]} rotation={[1.57, 0.337, 1.578]} scale={29.866}>
        <mesh geometry={nodes.Cube025_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube025_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[-58.05, 15.109, 77.705]} rotation={[1.567, 0.323, 1.579]} scale={29.866}>
        <mesh geometry={nodes.Cube026_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube026_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[-56.55, 15.613, 77.573]} rotation={[1.568, 0.339, 1.578]} scale={29.866}>
        <mesh geometry={nodes.Cube027_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube027_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[-59.156, 15.719, 77.456]} rotation={[1.569, 0.184, 1.579]} scale={29.866}>
        <mesh geometry={nodes.Cube027_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube027_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[-55.982, 15.468, 77.418]} rotation={[1.576, 0.343, 1.575]} scale={29.866}>
        <mesh geometry={nodes.Cube028_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube028_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[-59.789, 15.62, 77.492]} rotation={[1.569, 0.183, 1.579]} scale={29.866}>
        <mesh geometry={nodes.Cube029_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube029_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[-52.636, 15.553, 77.57]} rotation={[1.57, 0.337, 1.578]} scale={29.866}>
        <mesh geometry={nodes.Cube030_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube030_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[-52.959, 15.109, 77.705]} rotation={[1.567, 0.323, 1.579]} scale={29.866}>
        <mesh geometry={nodes.Cube031_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube031_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[-51.459, 15.613, 77.573]} rotation={[1.568, 0.339, 1.578]} scale={29.866}>
        <mesh geometry={nodes.Cube032_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube032_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[-54.065, 15.719, 77.456]} rotation={[1.569, 0.184, 1.579]} scale={29.866}>
        <mesh geometry={nodes.Cube032_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube032_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[-50.891, 15.468, 77.418]} rotation={[1.576, 0.343, 1.575]} scale={29.866}>
        <mesh geometry={nodes.Cube033_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube033_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[-54.698, 15.62, 77.492]} rotation={[1.569, 0.183, 1.579]} scale={29.866}>
        <mesh geometry={nodes.Cube034_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube034_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[-45.915, 15.553, 77.57]} rotation={[1.57, 0.337, 1.578]} scale={29.866}>
        <mesh geometry={nodes.Cube035_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube035_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[-46.238, 15.109, 77.705]} rotation={[1.567, 0.323, 1.579]} scale={29.866}>
        <mesh geometry={nodes.Cube036_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube036_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[-44.738, 15.613, 77.573]} rotation={[1.568, 0.339, 1.578]} scale={29.866}>
        <mesh geometry={nodes.Cube037_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube037_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[-47.344, 15.719, 77.456]} rotation={[1.569, 0.184, 1.579]} scale={29.866}>
        <mesh geometry={nodes.Cube037_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube037_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[-44.17, 15.468, 77.418]} rotation={[1.576, 0.343, 1.575]} scale={29.866}>
        <mesh geometry={nodes.Cube038_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube038_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[-47.977, 15.62, 77.492]} rotation={[1.569, 0.183, 1.579]} scale={29.866}>
        <mesh geometry={nodes.Cube039_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube039_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[73.661, 23.592, 77.45]} rotation={[1.568, 0.338, 1.578]} scale={29.866}>
        <mesh geometry={nodes.Cube043_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube043_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[71.076, 23.671, 77.492]} rotation={[1.569, 0.183, 1.579]} scale={29.866}>
        <mesh geometry={nodes.Cube043_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube043_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[72.815, 23.16, 77.705]} rotation={[1.567, 0.323, 1.579]} scale={29.866}>
        <mesh geometry={nodes.Cube044.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube044_1.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[74.316, 23.664, 77.573]} rotation={[1.568, 0.339, 1.578]} scale={29.866}>
        <mesh geometry={nodes.Cube045.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube045_1.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[74.884, 23.518, 77.418]} rotation={[1.576, 0.343, 1.575]} scale={29.866}>
        <mesh geometry={nodes.Cube046.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube046_1.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[70.563, 23.744, 77.511]} rotation={[1.569, 0.181, 1.58]} scale={29.866}>
        <mesh geometry={nodes.Cube055_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube055_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[66.795, 23.603, 77.57]} rotation={[1.57, 0.337, 1.578]} scale={29.866}>
        <mesh geometry={nodes.Cube056_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube056_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[66.472, 23.16, 77.705]} rotation={[1.567, 0.323, 1.579]} scale={29.866}>
        <mesh geometry={nodes.Cube057_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube057_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[67.972, 23.664, 77.573]} rotation={[1.568, 0.339, 1.578]} scale={29.866}>
        <mesh geometry={nodes.Cube058_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube058_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[65.366, 23.769, 77.456]} rotation={[1.569, 0.184, 1.579]} scale={29.866}>
        <mesh geometry={nodes.Cube058_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube058_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[68.54, 23.518, 77.418]} rotation={[1.576, 0.343, 1.575]} scale={29.866}>
        <mesh geometry={nodes.Cube059.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube059_1.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[64.733, 23.671, 77.492]} rotation={[1.569, 0.183, 1.579]} scale={29.866}>
        <mesh geometry={nodes.Cube060_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube060_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[60.547, 31.549, 77.57]} rotation={[1.57, 0.337, 1.578]} scale={29.866}>
        <mesh geometry={nodes.Cube061_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube061_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[60.223, 31.105, 77.705]} rotation={[1.567, 0.323, 1.579]} scale={29.866}>
        <mesh geometry={nodes.Cube062_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube062_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[61.724, 31.609, 77.573]} rotation={[1.568, 0.339, 1.578]} scale={29.866}>
        <mesh geometry={nodes.Cube063_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube063_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[59.118, 31.715, 77.456]} rotation={[1.569, 0.184, 1.579]} scale={29.866}>
        <mesh geometry={nodes.Cube063_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube063_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[62.292, 31.464, 77.418]} rotation={[1.576, 0.343, 1.575]} scale={29.866}>
        <mesh geometry={nodes.Cube064_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube064_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[58.485, 31.616, 77.492]} rotation={[1.569, 0.183, 1.579]} scale={29.866}>
        <mesh geometry={nodes.Cube065_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube065_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[60.547, 15.553, 77.57]} rotation={[1.57, 0.337, 1.578]} scale={29.866}>
        <mesh geometry={nodes.Cube066_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube066_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[60.223, 15.109, 77.705]} rotation={[1.567, 0.323, 1.579]} scale={29.866}>
        <mesh geometry={nodes.Cube067_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube067_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[61.724, 15.613, 77.573]} rotation={[1.568, 0.339, 1.578]} scale={29.866}>
        <mesh geometry={nodes.Cube068_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube068_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[59.118, 15.719, 77.456]} rotation={[1.569, 0.184, 1.579]} scale={29.866}>
        <mesh geometry={nodes.Cube068_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube068_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[62.292, 15.468, 77.418]} rotation={[1.576, 0.343, 1.575]} scale={29.866}>
        <mesh geometry={nodes.Cube069_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube069_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[58.485, 15.62, 77.492]} rotation={[1.569, 0.183, 1.579]} scale={29.866}>
        <mesh geometry={nodes.Cube070_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube070_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[65.638, 15.553, 77.57]} rotation={[1.57, 0.337, 1.578]} scale={29.866}>
        <mesh geometry={nodes.Cube071_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube071_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[65.314, 15.109, 77.705]} rotation={[1.567, 0.323, 1.579]} scale={29.866}>
        <mesh geometry={nodes.Cube072_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube072_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[67.383, 15.468, 77.418]} rotation={[1.576, 0.343, 1.575]} scale={29.866}>
        <mesh geometry={nodes.Cube073_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube073_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[63.576, 15.62, 77.492]} rotation={[1.569, 0.183, 1.579]} scale={29.866}>
        <mesh geometry={nodes.Cube074_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube074_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[72.359, 15.553, 77.57]} rotation={[1.57, 0.337, 1.578]} scale={29.866}>
        <mesh geometry={nodes.Cube075_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube075_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[72.036, 15.109, 77.705]} rotation={[1.567, 0.323, 1.579]} scale={29.866}>
        <mesh geometry={nodes.Cube076_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube076_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[73.536, 15.613, 77.573]} rotation={[1.568, 0.339, 1.578]} scale={29.866}>
        <mesh geometry={nodes.Cube077_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube077_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[70.93, 15.719, 77.456]} rotation={[1.569, 0.184, 1.579]} scale={29.866}>
        <mesh geometry={nodes.Cube077_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube077_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[70.297, 15.62, 77.492]} rotation={[1.569, 0.183, 1.579]} scale={29.866}>
        <mesh geometry={nodes.Cube078_1.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube078_2.geometry} material={materials['stacked paper']} />
      </group>
      <group position={[-17.536, 25.827, 85.828]} rotation={[Math.PI, 0, Math.PI]} scale={24.757}>
        <mesh geometry={nodes.Cube001.geometry} material={materials.wood} />
        <mesh geometry={nodes.Cube001_1.geometry} material={materials.glass} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials.iron} />
        <mesh geometry={nodes.Cube001_3.geometry} material={materials['sheet metal']} />
        <mesh geometry={nodes.Cube001_4.geometry} material={materials.hlinik} />
        <mesh geometry={nodes.Cube001_5.geometry} material={materials.guma} />
      </group>
      <group position={[5.186, 25.827, 85.828]} rotation={[Math.PI, 0, Math.PI]} scale={24.757}>
        <mesh geometry={nodes.Cube040_1.geometry} material={materials.wood} />
        <mesh geometry={nodes.Cube040_2.geometry} material={materials.glass} />
        <mesh geometry={nodes.Cube040_3.geometry} material={materials.iron} />
        <mesh geometry={nodes.Cube040_4.geometry} material={materials['sheet metal']} />
        <mesh geometry={nodes.Cube040_5.geometry} material={materials.hlinik} />
        <mesh geometry={nodes.Cube040_6.geometry} material={materials.guma} />
      </group>
    </group>
  )
}
export default Scene
useGLTF.preload('/newmodels/Scene.gltf')
