/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 stol_4.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Stol_4 =  (props: any) => {
  const { nodes, materials } = useGLTF('/newmodels/stol_4.gltf') as any
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.iron_table.geometry} material={materials['Artisan oak, kronospan, wood.']} position={[15.501, 8.057, 9.781]} scale={[0.523, 8.698, 0.523]} />
    </group>
  )
}

export default Stol_4
useGLTF.preload('/newmodels/stol_4.gltf')
