/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Woltmeter.gltf 
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import styles from "./Woltmeter.module.css";

const Woltmeter = (props: any) => {
    const ref = useRef() as any
  const { nodes, materials } = useGLTF('/newmodels/Woltmeter.gltf') as any
    const [data, setData] = useState<number>(0)
    const [click, setClick] = useState<boolean>(false)
    const getClick = () => {
        setClick(!click)
        if (click) {
            return (
                <p className={styles.datee}>Начальное значение {data} Вольт</p>
            )
        }
    }

    const changeData = () => {
        if (!click) {
            return (

                <p className={styles.datee}>Начальное значение {data} Вольт</p>
            )
        }
    }
  return (
    <group {...props}  dispose={null}>
      <group  position={[-12.899, 18.318, -15.378]}>
        <mesh
            geometry={nodes.Cube004.geometry}
            material={materials['Material.021']}
        />
        <mesh
            ref={ref}
            onClick={getClick}
            geometry={nodes.Cube004_1.geometry}
            material={materials['Material.022']}
        />
          <mesh
              geometry={nodes.Cube004_2.geometry}
              material={materials['Material.023']}
          />
      </group>
    </group>
  )
}
export default Woltmeter
useGLTF.preload('/newmodels/Woltmeter.gltf')
