/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 PlataCondera.glb 
*/

import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const CapacitorSurface = (props: any) => {
  const { nodes, materials } = useGLTF('/models/CapacitorSurface.glb') as any
  return (
    <group {...props} dispose={null}>
      <group position={[7.452, 18.324, -0.703]} rotation={[Math.PI, Math.PI / 2, 0]} scale={[-0.094, -0.001, -0.094]}>
        <mesh geometry={nodes.Основа_контакта_2003.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Основа_контакта_2003_1.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Основа_контакта_2003_2.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Основа_контакта_2003_3.geometry} material={materials['Material.006']} />
      </group>
    </group>
  )
}

export default CapacitorSurface

useGLTF.preload('/models/CapacitorSurface.glb')
