/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 contact_road_for_gun.glb 
*/


import {useRef, useState} from 'react'
import { useGLTF } from '@react-three/drei'

const ContactRoad = (props: any) => {
  const { nodes, materials } = useGLTF('/models/ContactRoad.glb') as any
    const [hover, setHover]=useState<boolean>(false)
    const [click, setClick]=useState<boolean>(false)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Основа_контакта_2.geometry} material={materials['Material.007']} position={[-5.599, 20.136, 4.637]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[-0.047, -0.003, -0.047]} />
      <group position={[-6.238, 20.136, 4.602]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[-0.044, -0.018, -0.044]}>
        <mesh geometry={nodes['Изолятор_контакта_#1_1'].geometry} material={materials['Material.009']} />
        <mesh geometry={nodes['Изолятор_контакта_#1_2'].geometry} material={materials['Material.007']} />
      </group>
    </group>
  )
}

export default ContactRoad

useGLTF.preload('/models/ContactRoad.glb')
