/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 stoiki_for_gun.glb 
*/


import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const DeskForGun = (props: any) => {
  const { nodes, materials } = useGLTF('/models/DeskForGun.glb') as any
  return (
    <group {...props} dispose={null}>
      <group position={[-0.428, 19.01, 5.583]} scale={[0.321, 1.148, 1.148]}>
        <mesh geometry={nodes.Ножка_пушки_1_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Ножка_пушки_1_2.geometry} material={materials['Material.004']} />
      </group>
    </group>
  )
}

export default DeskForGun

useGLTF.preload('/models/DeskForGun.glb')
