/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 Floor.glb 
*/

import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Floor = (props: any) => {
  const { nodes, materials } = useGLTF('/models/Floor.glb') as any
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane001.geometry} material={materials['Stone Walkway']} position={[-1.416, 0.469, 6.603]} scale={80.313} />
    </group>
  )
}

export default Floor

useGLTF.preload('/models/Floor.glb')
