/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 Floor.glb 
*/

import {useRef, useState} from 'react'
import { useGLTF } from '@react-three/drei'

const Floor = (props: any) => {
  const { nodes, materials } = useGLTF('/models/Floor.glb') as any
    const [hover, setHover]=useState<boolean>(false)
    const [click, setClick]=useState<boolean>(false)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane001.geometry}  material-color="#ffffff" material={materials['Stone Walkway']} position={[-1.416, 0.469, 6.603]} scale={80.313}>
          <meshStandardMaterial color="#FFFFFF" />
      </mesh>
    </group>
  )
}

export default Floor

useGLTF.preload('/models/Floor.glb')
