/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 stvol_gun.glb 
*/

import {useRef, useState} from 'react'
import { useGLTF } from '@react-three/drei'

const GunsTrunk = (props: any) => {
  const { nodes, materials } = useGLTF('/models/GunsTrunk.glb') as any
    const [hover, setHover]=useState<boolean>(false)
    const [click, setClick]=useState<boolean>(false)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Цилиндр_пушки.geometry} material={materials['Material.011']} position={[-3.413, 20.086, 5.578]} rotation={[0, 0, -Math.PI / 2]} scale={1.619} />
    </group>
  )
}


export default GunsTrunk

useGLTF.preload('/models/GunsTrunk.glb')
