/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 osnova_maiatnika.glb 
*/

import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const PendulumBasis= (props: any) => {
  const { nodes, materials } = useGLTF('/models/PendulumBasis.glb') as any
  return (
    <group {...props} dispose={null}>
      <group position={[4.457, 28.424, 5.846]} rotation={[Math.PI / 2, 0, 0]} scale={0.187}>
        <mesh geometry={nodes.Cylinder002.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cylinder002_1.geometry} material={materials.M_MetalRuler_SF} />
      </group>
    </group>
  )
}

export default PendulumBasis

useGLTF.preload('/models/PendulumBasis.glb')
