/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 Rozetka.glb 
*/

import {useRef, useState} from 'react'
import { useGLTF } from '@react-three/drei'

const PowerSocket = (props: any) => {
  const { nodes, materials } = useGLTF('/models/PowerSocket.glb') as any
    const [hover, setHover]=useState<boolean>(false)
    const [click, setClick]=useState<boolean>(false)
  return (
    <group {...props} dispose={null}>
      <group position={[-14.894, 18.177, 2.053]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.98, 0.303, 0.98]}>
        <mesh geometry={nodes.Розетка_1.geometry} material={materials['Material.016']} />
        <mesh geometry={nodes.Розетка_2.geometry} material={materials['Material.012']} />
      </group>
    </group>
  )
}

export default PowerSocket

useGLTF.preload('/models/PowerSocket.glb')
