/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 regulator_base.glb 
*/

import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const RegulatorBase = (props: any) => {
  const { nodes, materials } = useGLTF('/models/RegulatorBase.glb') as any
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Коробка_напряжения.geometry} material={materials['Material.008']} position={[-14.893, 18.189, 4.9]} rotation={[0, -1.571, 0]} scale={[1, 0.32, 1]} />
    </group>
  )
}

export default RegulatorBase

useGLTF.preload('/models/RegulatorBase.glb')
