/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 gruzikLeska.glb 
*/

import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const SinkerLine = (props: any) => {
  const { nodes, materials } = useGLTF('/models/SinkerLine.glb') as any
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder009.geometry} material={materials['Material.012']} position={[4.454, 20.094, 5.582]} rotation={[0, 0, -Math.PI / 2]} scale={[0.284, 0.639, 0.284]} />
    </group>
  )
}

export default SinkerLine

useGLTF.preload('/models/SinkerLine.glb')
