/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 Woltmeter.glb 
*/

import {useRef, useState} from 'react'
import { useGLTF } from '@react-three/drei'

const Voltmeter = (props: any) => {
  const { nodes, materials } = useGLTF('/models/Voltmeter.glb') as any
    const [hover, setHover]=useState<boolean>(false)
    const [click, setClick]=useState<boolean>(false)
  return (
    <group {...props} dispose={null}>
      <group position={[-11.686, 18.905, 4.665]}>
        <mesh geometry={nodes.Cube004.geometry} material={materials['Material.021']} />
        <mesh geometry={nodes.Cube004_1.geometry} material={materials['Material.022']} />
        <mesh geometry={nodes.Cube004_2.geometry} material={materials['Material.023']} />
      </group>
      <group position={[-11.686, 18.905, 4.665]}>
        <mesh geometry={nodes.Cube005.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Cube005_1.geometry} material={materials['Material.020']} />
      </group>
    </group>
  )
}

export default Voltmeter

useGLTF.preload('/models/Voltmeter.glb')
