/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 wires_automat_regulator.glb 
*/

import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import WiresForAutomatic from "./WiresForAutomatic";

const WiresForAutomatRegulator = (props: any) => {
  const { nodes, materials } = useGLTF('/models/WiresForAutomatRegulator.glb') as any
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.wiring_1002.geometry} material={materials['Material.015']} position={[-15.558, 18.07, 6.29]} rotation={[Math.PI / 2, 0, -3.142]} scale={[0.094, 0.608, 0.094]} />
    </group>
  )
}

export default WiresForAutomatRegulator

useGLTF.preload('/models/WiresForAutomatRegulator.glb')
